# -*- coding: utf-8 -*-
"""MiniProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KqGtecgj5IdD39MEbN_S1CSsObRS118

## **Mini project ภาพหมอก**

**โคลนโปรเจคจาก GitHub**
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/tranleanh/haze-synthesis.git
# %cd haze-synthesis

!ls

!pip install --upgrade pip setuptools wheel

"""**ติดตั้ง Dependencies**"""

!pip install torch torchvision numpy opencv-python matplotlib pillow

!ls /content

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/haze-synthesis

!ls /content/haze-synthesis/inputs

"""**สร้างภาพหมอกที่ beta = 1.0**"""

!python main.py --image_path ./inputs/1.jpg --output_image_path ./outputs/1_beta1.jpg --model_name mono+stereo_640x192 --beta 1.0 --airlight 150
!python main.py --image_path ./inputs/2.jpg --output_image_path ./outputs/2_beta1.jpg --model_name mono+stereo_640x192 --beta 1.0 --airlight 150
!python main.py --image_path ./inputs/3.jpg --output_image_path ./outputs/3_beta1.jpg --model_name mono+stereo_640x192 --beta 1.0 --airlight 150
!python main.py --image_path ./inputs/4.jpg --output_image_path ./outputs/4_beta1.jpg --model_name mono+stereo_640x192 --beta 1.0 --airlight 150
!python main.py --image_path ./inputs/5.jpg --output_image_path ./outputs/5_beta1.jpg --model_name mono+stereo_640x192 --beta 1.0 --airlight 150
!python main.py --image_path ./inputs/6.jpg --output_image_path ./outputs/6_beta1.jpg --model_name mono+stereo_640x192 --beta 1.0 --airlight 150

"""**สร้างภาพหมอกที่ beta = 1.5**"""

!python main.py --image_path ./inputs/1.jpg --output_image_path ./outputs/1_beta1.5.jpg --model_name mono+stereo_640x192 --beta 1.5 --airlight 150
!python main.py --image_path ./inputs/2.jpg --output_image_path ./outputs/2_beta1.5.jpg --model_name mono+stereo_640x192 --beta 1.5 --airlight 150
!python main.py --image_path ./inputs/3.jpg --output_image_path ./outputs/3_beta1.5.jpg --model_name mono+stereo_640x192 --beta 1.5 --airlight 150
!python main.py --image_path ./inputs/4.jpg --output_image_path ./outputs/4_beta1.5.jpg --model_name mono+stereo_640x192 --beta 1.5 --airlight 150
!python main.py --image_path ./inputs/5.jpg --output_image_path ./outputs/5_beta1.5.jpg --model_name mono+stereo_640x192 --beta 1.5 --airlight 150
!python main.py --image_path ./inputs/6.jpg --output_image_path ./outputs/6_beta1.5.jpg --model_name mono+stereo_640x192 --beta 1.5 --airlight 150

"""**สร้างภาพหมอกที่ beta = 2.0**"""

!python main.py --image_path ./inputs/1.jpg --output_image_path ./outputs/1_beta2.0.jpg --model_name mono+stereo_640x192 --beta 2.0 --airlight 150
!python main.py --image_path ./inputs/2.jpg --output_image_path ./outputs/2_beta2.0.jpg --model_name mono+stereo_640x192 --beta 2.0 --airlight 150
!python main.py --image_path ./inputs/3.jpg --output_image_path ./outputs/3_beta2.0.jpg --model_name mono+stereo_640x192 --beta 2.0 --airlight 150
!python main.py --image_path ./inputs/4.jpg --output_image_path ./outputs/4_beta2.0.jpg --model_name mono+stereo_640x192 --beta 2.0 --airlight 150
!python main.py --image_path ./inputs/5.jpg --output_image_path ./outputs/5_beta2.0.jpg --model_name mono+stereo_640x192 --beta 2.0 --airlight 150
!python main.py --image_path ./inputs/6.jpg --output_image_path ./outputs/6_beta2.0.jpg --model_name mono+stereo_640x192 --beta 2.0 --airlight 150

"""**ดาวน์โหลดไฟล์ที่สร้างเสร็จ**"""

from google.colab import files
import os
for file in os.listdir('./outputs'):
    files.download(f'./outputs/{file}')